Project_Summer/Areas/Admin/Controllers/ProviderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project_Summer.DataContext;

namespace Project_Summer.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProviderController : Controller
    {
        private SummerrContext _context;
        public ProviderController(SummerrContext context)
        {
           
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
           
            return View(await _context.NhaCungCaps.ToListAsync());
        }
        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NhaCungCap model)
        {
            // nếu thông tin điền đúng thì thực hiện 

            if (ModelState.IsValid)
            {
                
                var TenLoaiAlias = await _context.NhaCungCaps.FirstOrDefaultAsync(p => p.TenCongTy == model.TenCongTy);
                if (TenLoaiAlias != null)
                { // sp đẫ tồn tại
                    ModelState.AddModelError("", "Nhà cung cấp đã có trong database");
                    return View(model);
                }
                _context.NhaCungCaps.Add(model);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Message"] = "Thông tin chưa đúng";
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var ncc = await _context.NhaCungCaps.FindAsync(id);

            return View(ncc);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(NhaCungCap model, int id)
        {
            // nếu thông tin điền đúng thì thực hiện 

            if (ModelState.IsValid)
            {
                var ncc = await _context.NhaCungCaps.FindAsync(id);

            
                var existingNcc = await _context.NhaCungCaps.FirstOrDefaultAsync(p => p.TenCongTy == model.TenCongTy && p.MaNcc != id);
                if (existingNcc != null)
                { // sp đẫ tồn tại
                    ModelState.AddModelError("", "Sản phẩm đã có trong database");
                    return View(model);
                }
                ncc.TenCongTy = model.TenCongTy;
               ncc.NguoiLienLac = model.NguoiLienLac;
                ncc.MoTa = model.MoTa;
                ncc.DiaChi = model.DiaChi;


                try
                {
                    _context.NhaCungCaps.Update(ncc);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // Xử lý ngoại lệ nếu có vấn đề khi cập nhật
                    ModelState.AddModelError("", "Có lỗi khi cập nhật: " + ex.Message);
                }
            }
            else
            {
                TempData["Message"] = "Thông tin chưa đúng";
            }
            return View(model);
        }
        public async Task<IActionResult> Delete(string id)
        {
            NhaCungCap ncc = _context.NhaCungCaps.Find(id);
            // Kiểm tra nếu sản phẩm đã tồn tại trong giỏ hàng hoặc bảng chi tiết hóa đơn
           // bool LoaiInOrder = _context.ChiTietHds.Any(ct => ct.MaCt == id); // Bảng ChiTietHd
            /*      bool productInCart = _context.GioHang.Any(gh => gh.MaHh == id);    // Bảng Giỏ hàng (nếu có)*/

/*            if (LoaiInOrder)
            {
                // Thông báo nếu sản phẩm đã được đặt trong giỏ hàng hoặc hóa đơn
                TempData["Message"] = "Không thể xóa sản phẩm này vì nó đã được đặt trong giỏ hàng hoặc hóa đơn.";
                return RedirectToAction("Index");
            }*/

            _context.NhaCungCaps.Remove(ncc);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Project_Summer/Areas/Admin/Views/Provider/Create.cshtml
@model Project_Summer.DataContext.NhaCungCap

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Thêm mới nhà cung cấp</h1>
@TempData["Message"]
<h4>Tại sản phẩm</h4>
<div class="col-md-9">
    <form asp-action="Create" asp-controller="Provider" enctype="multipart/form-data">
        <div class="form-group">
            <label>Tên công ty</label>
            <input asp-for="TenCongTy" class="form-control" />
            <span asp-validation-for="TenCongTy" class="text-danger" />
        </div>

        <div class="form-group">
            <label>Thông tin liên lạc</label>
            <input asp-for="NguoiLienLac" class="form-control" />
            <span asp-validation-for="NguoiLienLac" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Logo</label>
            <input asp-for="Logo" class="form-control" />
            <span asp-validation-for="Logo" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Email</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Số điện thoại</label>
            <input asp-for="DienThoai" class="form-control" />
            <span asp-validation-for="DienThoai" class="text-danger" />
        </div>

        <div class="form-group">
            <label>Địa chỉ</label>
            <input asp-for="DiaChi" class="form-control" />
            <span asp-validation-for="DiaChi" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Mô tả</label>
            <textarea asp-for="MoTa" class="form-control"></textarea>
            <span asp-validation-for="MoTa" class="text-danger" />
        </div>
        <div class="form-group ">
            <button type="submit" class="btn btn-primary ">Tạo sản phẩm</button>
        </div>

    </form>

</div>

Project_Summer/Areas/Admin/Views/Provider/Edit.cshtml
@model Project_Summer.DataContext.NhaCungCap
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<h1>Chỉnh sửa thông tin Nhà cung cấp</h1>
@TempData["Message"]
<div class="col-md-9">
    <form asp-action="Edit" asp-controller="Provider" enctype="multipart/form-data">
        <div class="form-group">
            <label>Tên Coong ty</label>
            <input asp-for="TenCongTy" class="form-control" />
            <span asp-validation-for="TenCongTy" class="text-danger" />
        </div>

        <div class="form-group">
            <label>Logo đại diện</label>
            <input asp-for="Logo" class="form-control" />
            <span asp-validation-for="Logo" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Người liên lạc</label>
            <input asp-for="NguoiLienLac" class="form-control" />
            <span asp-validation-for="NguoiLienLac" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Email</label>
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Số điện thoại</label>
            <input asp-for="DienThoai" class="form-control" />
            <span asp-validation-for="DienThoai" class="text-danger" />
        </div>
        <div class="form-group">
            <label>Địa chỉ</label>
            <input asp-for="DiaChi" class="form-control" />
            <span asp-validation-for="DiaChi" class="text-danger" />
        </div>

        <div class="form-group">
            <label>Mô tả</label>
            <textarea asp-for="MoTa" class="form-control"></textarea>
            <span asp-validation-for="MoTa" class="text-danger" />
        </div>
        <div class="form-group ">
            <button type="submit" class="btn btn-primary ">Lưu Nhà cung cấp</button>
        </div>

    </form>

</div>

Project_Summer/Areas/Admin/Views/Provider/Index.cshtml
@model IEnumerable<Project_Summer.DataContext.NhaCungCap>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<h4>Bảng thông tin Các nhà cung cấp</h4>
<a asp-controller="Provider" asp-action="Create">Thêm Loại sản phẩm</a>
<table class="table table-bordered" id="myTable">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Mã Ncc</th>
            <th scope="col">Tên Ncc</th>
            <th scope="col">Logo </th>
            <th scope="col">Liên lạc</th>
            <th scope="col">Email</th>
            <th scope="col">Điện thoại</th>
            <th scope="col">Địa chỉ</th>
            <th scope="col">Mô tả</th>
            <th scope="col">Tùy chọn</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <th scope="row">@item.MaNcc</th>
                <td>@item.TenCongTy</td>
                <td><img src="~/img/@item.Logo" /></td>
                <td>@item.NguoiLienLac</td>
                <td>@item.Email</td>
                <td>@item.DienThoai</td>
                <td>@item.DiaChi</td>
                <td>@item.MoTa</td>

                <td>
                    <a asp-controller="Provider" class="btn btn-warning btn-sm" asp-action="Edit" asp-route-id="@item.MaNcc">Sửa</a>
                    <a asp-controller="Provider" class="btn btn-danger btn-sm confirmDeletion" asp-action="Delete" asp-route-id="@item.MaNcc">Xóa</a>
                </td>
            </tr>

        }
    </tbody>
</table>