Project_Summer/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project_Summer.DataContext;

namespace Project_Summer.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrderController : Controller
    {
        private SummerrContext _context;
        public OrderController(SummerrContext context) {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var hoadon = await _context.HoaDons.OrderByDescending(p => p.MaHd).ToListAsync();
            return View(hoadon);
        }
        public async Task<IActionResult> Details(int id)
        {
            var detail = await _context.ChiTietHds.Include(p => p.MaHhNavigation).Where(hd => hd.MaHd == id).ToListAsync();
            return View(detail);
        }
        // xóa đơn hàng
       
        public  IActionResult Delete(int id)
        {
            // xóa chi tiết đơn hàng
            var hd = _context.HoaDons.Include(p => p.ChiTietHds).Where(p => p.MaHd == id).FirstOrDefault();
            if(hd == null)
            {
                ViewBag.message = " không tìm thấy đơn hàng";
            }
            foreach(var ct in hd.ChiTietHds.ToList())
            {
                _context.ChiTietHds.Remove(ct);
            }
            // xóa đơn hàng
            _context.HoaDons.Remove(hd);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Project_Summer/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Project_Summer.DataContext;
using Project_Summer.Helper;
using Project_Summer.Models;
using Project_Summer.Repository;
using System.Linq;
using System.Security.Claims;

namespace Project_Summer.Controllers
{
    public class CartController : Controller
    {
        private SummerrContext _context;
        private readonly IEmailSender _emailSender;
        private readonly PaypalClient _paypalClient;

        public CartController(SummerrContext context, IEmailSender emailSender, PaypalClient paypalClient)
        {
            _context = context;
            _emailSender = emailSender;
            _paypalClient = paypalClient;
        }
        public IActionResult Index()
        {
            var GioHang = Cart; // Lấy giỏ hàng từ session
            var shippingPriceCookie = Request.Cookies["shippingPrice"];
            double shippingPrice = 0;
            if (shippingPriceCookie != null) {
                var shippingPicejson = shippingPriceCookie;
                shippingPrice = JsonConvert.DeserializeObject<double>(shippingPicejson);
            }
            ViewBag.ShippingPrice = shippingPrice;
            return View(GioHang);
        }

        public List<CartItem> Cart => HttpContext.Session.Get<List<CartItem>>(ConstModel.CART_KEY) ?? new List<CartItem>();

        public IActionResult AddToCart(int idHH, int SoLuong = 1)
        {
            var GioHang = Cart;
            var item = Cart.SingleOrDefault(p => p.IDhh == idHH);
            if (item == null)
            {
                var hanghoa = _context.HangHoas.SingleOrDefault(p => p.MaHh == idHH);
                if (hanghoa == null)
                {
                    return NotFound();
                }
                item = new CartItem
                {
                    IDhh = hanghoa.MaHh,
                    Hinh = hanghoa.Hinh ?? string.Empty,
                    DonGia = hanghoa.DonGia ?? 0,
                    Soluong = SoLuong,
                    Tenhh = hanghoa.TenHh
                };
                GioHang.Add(item);

            }
            else
            {
                // tăng số lươngj
                item.Soluong += SoLuong;
            }
            TempData["Message"] = "Thêm giỏ hàng thành công";
            HttpContext.Session.Set(ConstModel.CART_KEY, GioHang);// lưu session
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var GioHang = Cart;
            var item = Cart.SingleOrDefault(p => p.IDhh == id);
            if (item != null)
            {
                GioHang.Remove(item);
                HttpContext.Session.Set(ConstModel.CART_KEY, GioHang);// lưu session
            }
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Customer")]
        [HttpGet]
        public IActionResult CheckOut()
        {
            if (Cart.Count == 0)
            {
                return Redirect("/");
            }
            ViewBag.PaypalClientId = _paypalClient.ClientId;

            return View(Cart);
        }
        [HttpPost]
        public async Task<IActionResult> CheckOut(CheckOutVM model, double TongTien)
        {
            if (ModelState.IsValid)
            {
                
                var idkh = HttpContext.User.Claims.SingleOrDefault(id => id.Type == ConstModel.CLAIM_IDUSER).Value;
                if (idkh == null)
                {
                    // Handle the case where the user is not logged in or the claim is missing
                    return RedirectToAction("Login", "Account");
                }

                var khachhang = new KhachHang();
                if (model.GiongKhachHang)
                {
                    khachhang = _context.KhachHangs.SingleOrDefault(kh => kh.MaKh == idkh);
                }
                var shippingPriceCookie = Request.Cookies["shippingPrice"];
                double shippingPrice = 0;
                if (shippingPriceCookie != null)
                {
                    var shippingPicejson = shippingPriceCookie;
                    shippingPrice = JsonConvert.DeserializeObject<double>(shippingPicejson);
                }
                ViewBag.tongcong = TongTien;
                ViewBag.ShippingPrice = shippingPrice;
                var hoadon = new HoaDon()
                {
                    MaKh = idkh,
                    NgayDat = DateTime.Now,
                    HoTen = model.Hoten ?? khachhang.HoTen,
                    DiaChi = model.DiaChi ?? khachhang.DiaChi,
                    DienThoai = model.DienThoai ?? khachhang.DienThoai,
                    TongTien = TongTien,
                    CachThanhToan = "COD",
                    CachVanChuyen = "GRAP",
                    MaTrangThai = 0,
                    PhiVanChuyen=shippingPrice,
                    GhiChu = model.GhiChu

                };

                _context.Database.BeginTransaction();
                try
                {
                    _context.Database.CommitTransaction();
                    _context.Add(hoadon);
                    _context.SaveChanges();
                    var ChiTietHD = new List<ChiTietHd>();
                    foreach (var item in Cart)
                    {
                        ChiTietHD.Add(new ChiTietHd
                        {
                            MaHd = hoadon.MaHd,
                            SoLuong = item.Soluong,
                            DonGia = item.DonGia,
                            HinhHh = item.Hinh,
                            MaHh = item.IDhh,
                            GiamGia = 0
                        });
                        var sp = _context.HangHoas.Where(sp => sp.MaHh == item.IDhh).FirstOrDefault();
                        if (sp != null)
                        {
                            sp.SoLuong -= item.Soluong;
                            sp.DaBan += item.Soluong;
                            _context.Update(sp);
                        }
                        _context.Update(sp);
                    };

                    _context.AddRange(ChiTietHD);
                    _context.SaveChanges();                 // là từ khóa hay gọi là sessionID 
                    HttpContext.Session.Set<List<CartItem>>(ConstModel.CART_KEY, Cart);// Khi bạn thực hiện yêu cầu tiếp theo, Session ID từ cookie được gửi kèm, và server sử dụng nó để tìm và truy xuất dữ liệu session tương ứng.

                    var receiver = "nhi880031@gmail.com";
                    var subject = "Bạn đã đặt hàng thành công";
                    var message = "Mọi Thắc mắc xin liện hệ cho chúng tôi qua : +098765422";
                    await _emailSender.SendEmailAsync(receiver, subject, message);

                    return RedirectToAction("Success");
                }
                catch (Exception ex)
                {
                    _context.Database.RollbackTransaction();
                }

            }
            return View(Cart);
        }
        [Authorize]
        [HttpPost("/Cart/create-paypal-order")]
        public async Task<IActionResult> CreatePaypalOrder(CancellationToken cancellationToken)
        {
            // thông tin đơn hàng gửi qua paypal
            var tongtien = Cart.Sum(p => p.ThanhTien).ToString();
            var donvitien = "USD";
            var maDonHnagThamChieu = "DH" + DateTime.Now.Ticks.ToString();
            try
            {
                var response = await _paypalClient.CreateOrder(tongtien, donvitien, maDonHnagThamChieu);
                return Ok(response);
            }
            catch (Exception ex)
            {
                var error = new { ex.GetBaseException().Message };
                return BadRequest(error);
            }
        }
        // lưu đơn hàng
        [Authorize]
        [HttpPost("/Cart/capture-paypal-order")]
        public async Task<IActionResult> CapturePaypalOrder(string orderID, CancellationToken cancellationToken)
        {
            try
            {
                var response = await _paypalClient.CaptureOrder(orderID);
                if (response.status.ToLower() != "completed")
                {
                    throw new Exception("Thanh toán PayPal không thành công.");
                }

                // Lấy ID khách hàng từ claims
                var idkh = HttpContext.User.Claims.SingleOrDefault(id => id.Type == ConstModel.CLAIM_IDUSER).Value;
                if (idkh == null)
                {
                    // Handle the case where the user is not logged in or the claim is missing
                    return RedirectToAction("DangNhap", "KhachHang");
                }

                // Lấy thông tin khách hàng từ cơ sở dữ liệu
                var khachHang = _context.KhachHangs.SingleOrDefault(kh => kh.MaKh == idkh);
                if (khachHang == null)
                {
                    ModelState.AddModelError("", "Khách hàng không tồn tại.");
                    return BadRequest(new { Message = "Khách hàng không tồn tại." });
                }

                // Tạo hóa đơn mới
                var hoadon = new HoaDon
                {
                    MaKh = idkh,
                    HoTen = khachHang.HoTen,
                    DiaChi = khachHang.DiaChi,
                    DienThoai = khachHang.DienThoai,
                    NgayDat = DateTime.Now,
                    CachThanhToan = "PayPal",
                    CachVanChuyen = "GRAB",
                    MaTrangThai = 0,
                    GhiChu = "Thanh toán qua PayPal"
                };

                _context.Add(hoadon);
                _context.SaveChanges();
                // Tạo chi tiết hóa đơn từ giỏ hàng
                var ChiTietHD = new List<ChiTietHd>();
                foreach (var item in Cart)

Project_Summer/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project_Summer.DataContext;
using Project_Summer.Models;
using System;

namespace Project_Summer.Controllers
{
    public class ProductController : Controller
    {
        private SummerrContext _context;
        public ProductController(SummerrContext context)
        {
            _context = context;
        }
        public IActionResult Index(int? loai)
        {
            var hanghoas = _context.HangHoas.AsQueryable();
            if(loai.HasValue)
            {
                hanghoas = hanghoas.Where(p => p.MaLoai == loai.Value);
            }

            var data = hanghoas.Select(p => new HangHoaVM
            {
                IdHH = p.MaHh,
                TenHH = p.TenHh,
                TenLoai = p.MaLoaiNavigation.TenLoai,
                Hinh = p.Hinh ?? " ",
                GiaHH = p.DonGia ?? 0,
                MoTa = p.MoTa ?? "",
                SoLuong = p.SoLuong


            });
            return View(data);
        }
        public IActionResult Detail(int? id)
        {
            var product = _context.HangHoas
               .Include(p =>p.MaLoaiNavigation)
               .Include(p =>p.NhanXets)
                .SingleOrDefault( p => p.MaHh == id);// tìm sp trong db
           /* if(product == null)
            {
                return RedirectToAction("Loi","Home");
            }*/
            var datas = new HangHoaDetailVM 
            {
                IdHH = product.MaHh,
                TenHH = product.TenHh,
                GiaHH = product.DonGia ?? 0,
                Hinh = product.Hinh ?? " ",
                Mota = product.MoTa ?? " ",
                TenLoai = product.MaLoaiNavigation.TenLoai
            };
            // Gói HangHoaDetailVM vào ProductDetailVM
            var productDetailVM = new ProductDetailVM
            {
                HangHoaDetailVM = datas,
                HoTen = "", // Chưa có thông tin, để trống
                Email = "", // Chưa có thông tin, để trống
                NoiDung = "" // Chưa có nội dung đánh giá, để trống
            };
            return View(productDetailVM);

        }
        [HttpPost]
        public IActionResult Reviews(ProductDetailVM model)
        {
            if (ModelState.IsValid)
            {
                if (model.HangHoaDetailVM == null)
                {
                    // Xử lý khi HangHoaDetailVM là null
                    ViewBag.Message = "Có lỗi xảy ra, vui lòng thử lại.";
                    return RedirectToAction("Detail", new { id = model.HangHoaDetailVM?.IdHH });
                }
                var data = new NhanXet
                {
                    MaHh = model.HangHoaDetailVM.IdHH,
                    HoTen = model.HoTen,
                    Email = model.Email,
                    NoiDung = model.NoiDung,
                    NgayDang = DateTime.Now,
                };
                _context.NhanXets.Add(data);
                _context.SaveChanges();
            }
            ViewBag.Message = "Thêm đánh giá thành công";
            return RedirectToAction("Detail",  new { id = model.HangHoaDetailVM.IdHH });
        }
        public async Task<IActionResult> Search(string searchform)
        {
            // Kiểm tra xem từ khóa tìm kiếm có rỗng không
            if (string.IsNullOrEmpty(searchform))
            {
                return RedirectToAction("Index"); // Nếu không có từ khóa, trả về trang chính
            }
            var products = await _context.HangHoas
                .Where(p => p.TenHh.Contains(searchform) || p.MoTa.Contains(searchform))
                .Select(p => new HangHoaVM
                {
                    IdHH = p.MaHh,
                    TenHH = p.TenHh,
                    TenLoai = p.MaLoaiNavigation.TenLoai,
                    Hinh = p.Hinh ?? " ",
                    GiaHH = p.DonGia ?? 0,
                    MoTa = p.MoTa ?? ""
                })
                .ToListAsync();
            ViewBag.Key = searchform; 
            return View(products);
        }

    }
}

Project_Summer/Areas/Admin/Views/Shared/ProductItem.cshtml
@model IEnumerable<Project_Summer.Models.HangHoaVM>

 <h3></h3>
@foreach (var item in Model)
{
    <div class="col-md-6 col-lg-6 col-xl-4">
        <div class="rounded position-relative fruite-item">
            <a asp-action="Detail" asp-controller="Product" asp-route-id="@item.IdHH">
            <div class="fruite-img">
                <img src="~/img/@item.Hinh" class="img-fluid w-100 rounded-top" alt="">
            </div>
            </a>
            <div class="text-white bg-secondary px-3 py-1 rounded position-absolute" style="top: 10px; left: 10px;">@item.TenLoai</div>
            <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                 <a asp-action="Detail" asp-controller="Product" asp-route-id="@item.IdHH">
                <h4>@item.TenHH</h4>
                </a>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt</p>
                <div class="d-flex justify-content-between flex-lg-wrap">
                    <p class="text-dark fs-5 fw-bold mb-0">@item.GiaHH</p>
                    <a asp-action="AddToCart" asp-controller="Cart" asp-route-idHH="@item.IdHH" class="btn border border-secondary rounded-pill px-3 text-primary"><i class="fa fa-shopping-bag me-2 text-primary"></i> Add to cart</a>
                </div>
            </div>
        </div>
    </div>
}

Project_Summer/Areas/Admin/Views/Shared/Succees.cshtml
@{
    ViewData["Title"] = "Succees";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Succees</h1>

Project_Summer/Areas/Admin/Views/Shared/_Footer.cshtml
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5">
    <div class="container py-5">
        <div class="pb-4 mb-4" style="border-bottom: 1px solid rgba(226, 175, 24, 0.5) ;">
            <div class="row g-4">
                <div class="col-lg-3">
                    <a href="#">
                        <h1 class="text-primary mb-0">Fruitables</h1>
                        <p class="text-secondary mb-0">Fresh products</p>
                    </a>
                </div>
                <div class="col-lg-6">
                    <div class="position-relative mx-auto">
                        <input class="form-control border-0 w-100 py-3 px-4 rounded-pill" type="number" placeholder="Your Email">
                        <button type="submit" class="btn btn-primary border-0 border-secondary py-3 px-4 position-absolute rounded-pill text-white" style="top: 0; right: 0;">Subscribe Now</button>
                    </div>
                </div>
                <div class="col-lg-3">
                    <div class="d-flex justify-content-end pt-3">
                        <a class="btn  btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-facebook-f"></i></a>
                        <a class="btn btn-outline-secondary me-2 btn-md-square rounded-circle" href=""><i class="fab fa-youtube"></i></a>
                        <a class="btn btn-outline-secondary btn-md-square rounded-circle" href=""><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Why People Like us!</h4>
                    <p class="mb-4">
                        typesetting, remaining essentially unchanged. It was
                        popularised in the 1960s with the like Aldus PageMaker including of Lorem Ipsum.
                    </p>
                    <a href="" class="btn border-secondary py-2 px-4 rounded-pill text-primary">Read More</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Shop Info</h4>
                    <a class="btn-link" href="">About Us</a>
                    <a class="btn-link" href="">Contact Us</a>
                    <a class="btn-link" href="">Privacy Policy</a>
                    <a class="btn-link" href="">Terms & Condition</a>
                    <a class="btn-link" href="">Return Policy</a>
                    <a class="btn-link" href="">FAQs & Help</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="d-flex flex-column text-start footer-item">
                    <h4 class="text-light mb-3">Account</h4>
                    <a class="btn-link" href="">My Account</a>
                    <a class="btn-link" href="">Shop details</a>
                    <a class="btn-link" href="">Shopping Cart</a>
                    <a class="btn-link" href="">Wishlist</a>
                    <a class="btn-link" href="">Order History</a>
                    <a class="btn-link" href="">International Orders</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <div class="footer-item">
                    <h4 class="text-light mb-3">Contact</h4>
                    <p>Address: 1429 Netus Rd, NY 48247</p>
                    <p>Email: Example@gmail.com</p>
                    <p>Phone: +0123 4567 8910</p>
                    <p>Payment Accepted</p>
                    <img src="img/payment.png" class="img-fluid" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

Project_Summer/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Fruitables - Vegetable Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css" rel="stylesheet">
    
    <link href="//cdn.datatables.net/2.1.7/css/dataTables.dataTables.min.css" rel="stylesheet">
   @*  <link href="https://cdn.datatables.net/2.1.7/css/dataTables.dataTables.css" rel="stylesheet"> *@
    <link href="https://cdn.datatables.net/buttons/3.1.2/css/buttons.dataTables.css" rel="stylesheet">
    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
</head>
<body>

    <!-- Navbar start -->
    <div class="container-fluid fixed-top">
        <div class="container topbar bg-primary d-none d-lg-block">
            <div class="d-flex justify-content-between">
                <div class="top-info ps-2">
                    <small class="me-3"><i class="fas fa-map-marker-alt me-2 text-secondary"></i> <a href="#" class="text-white">123 Street, New York</a></small>
                    <small class="me-3"><i class="fas fa-envelope me-2 text-secondary"></i><a href="#" class="text-white">Email@Example.com</a></small>
                </div>
                <div class="top-link pe-2">
                    <a href="#" class="text-white"><small class="text-white mx-2">Privacy Policy</small>/</a>
                    <a href="#" class="text-white"><small class="text-white mx-2">Terms of Use</small>/</a>
                    <a href="#" class="text-white"><small class="text-white ms-2">Sales and Refunds</small></a>
                </div>
            </div>
        </div>
        <div class="container px-0">
            <nav class="navbar navbar-light bg-white navbar-expand-xl">
                <a href="index.html" class="navbar-brand"><h1 class="text-primary display-6">Fujjii</h1></a>
                <button class="navbar-toggler py-2 px-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars text-primary"></span>
                </button>
                <div class="collapse navbar-collapse bg-white" id="navbarCollapse">
                    <div class="navbar-nav mx-auto">
                        <a href="/" class="nav-item nav-link active">Trang chủ</a>
                        <a asp-area="Admin" asp-controller="ProductManager" asp-action="Index" class="nav-item nav-link">Quản lys sản phẩm</a>
                        <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="nav-item nav-link">Loại sản phẩm</a>
                        <a asp-area="Admin" asp-controller="Provider" asp-action="Index" class="nav-item nav-link">Nhà cung cấp</a>
                        <a asp-area="Admin" asp-controller="Order" asp-action="Index" class="nav-item nav-link">Đơn hàng</a>
                        <a asp-area="Admin" asp-controller="Shipping" asp-action="Index" class="nav-item nav-link">Phí vận chuyển</a>
                        
                    </div>

                    @await Component.InvokeAsync("Cart")
                    <a asp-controller="KhachHang" asp-action="DangNhap" class="my-auto">
                        <i class="fas fa-user fa-2x"></i>
                    </a>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->



    <div class="container">
        <main role="main" class="pb-3" style="margin-top: 200px;">
            @RenderBody()
        </main>
    </div>

   @await Html.PartialAsync("_Footer")
    <!-- JavaScript Libraries -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/2.1.7/js/dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/dataTables.buttons.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.dataTables.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/3.1.2/js/buttons.print.min.js"></script>
    
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/Backend/js/site.js"></script>
    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
    <script>
        $(function () {
            var message = '@TempData["Message"]';
            if (message! = '') { 
                Swal.file(message)
            };
        })
    </script>
    @await RenderSectionAsync("Scripts", required: false)

        <script>
            let table = new DataTable('#myTable', {
                layout: {
                    topStart: {
                        buttons: ['copy', 'csv', 'excel', 'pdf', 'print']
                    }
                }
            });
        </script>


   
</body>
</html>